
on:
  push:
    branches: [refactor/fastapi]

jobs:
  login-to-ecr:
    name: Configure AWS and Login to ECR
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public


  build-image:
    name: Build and Tag Docker Image
    runs-on: ubuntu-latest
    needs: [login-to-ecr]
    env:
      REGISTRY: public.ecr.aws
      REGISTRY_ALIAS: a4q2d8e1
      REPOSITORY: ${{steps.login-to-ecr.outputs.registry}}
      IMAGE_TAG: ${{github.sha}}
    run:
      docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .


  # push-image:
  #   needs: [login-to-ecr, build-image]
  #   runds-on: ubuntu-latest
  #   env:
  #     REGISTRY: public.ecr.aws
  #     REGISTRY_ALIAS: a4q2d8e1
  #     REPOSITORY: ${{steps.login-to-ecr.outputs.registry}}
  #     IMAGE_TAG: ${{github.sha}}
  #   run:
  #     docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG