
on:
  push:
    branches: [refactor/fastapi]

jobs:
  login-to-ecr:
    name: Configure AWS and Login to ECR
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

  build-and-push-image:
    name: Build and Tag Docker Image
    runs-on: ubuntu-latest
    needs: [login-to-ecr]
    env:
      REGISTRY: public.ecr.aws
      REGISTRY_ALIAS: ${{secrets.ECR_REGISTRY_ALIAS}}
      REPOSITORY: ${{steps.login-to-ecr.outputs.registry}}
      IMAGE_TAG: ${{github.sha}}
    steps:
    - name: Build Docker Image
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .

    - name: Push Docker Image to ECR
      run: |
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
