
on:
  push:
    branches: [refactor/fastapi]

jobs:
  login-to-ecr:
    name: Login to ECR, Build Image and Push to ECR
    runs-on: ubuntu-latest
    env:
      REPOSITORY: public.ecr.aws
      REPOSITORY_ALIAS: ${{secrets.ECR_REPOSITORY_ALIAS}}
      REPOSITORY_NAME: ${{secrets.ECR_REPOSITORY_NAME}}
      IMAGE_TAG: ${{github.sha}}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public
    
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker Image
      id: build-image
      run: |
        docker build -t $REPOSITORY/$REPOSITORY_ALIAS/$REPOSITORY_NAME:$IMAGE_TAG .

    - name: Push Docker Image to ECR
      run: |
        docker push $REPOSITORY/$REPOSITORY_ALIAS/$REPOSITORY_NAME:$IMAGE_TAG

    - name: install more-utils
      run: sudo apt-get -y install moreutils

    - name: Update python-server image ID in ecr_task_definition.json
      run: |
        jq --arg image_name "$REPOSITORY/$REPOSITORY_ALIAS/$REPOSITORY_NAME" \
          --arg image_tag "$IMAGE_TAG" \
          '.containerDefinitions[3].image=$image_name:image_tag' \
          ecr_task_definition.json | sponge ecr_task_definition.json

    - name: read ecr_task_definition json
      run: cat ecr_task_definition.json